### ISSUE TITLE
ImportError: No module named autocomplete_light

### ISSUE THREAD

**Issue by mjgorman** [philchristensen/antioch#4]
Current master, clean docker-compose up results in errors about giving up since apps haven't started. Tracked it back to autocomplete_light import error. Seems like something isn't compatible between versions somewhere.

**Comment by philchristensen** [comment]
I've recently put in place a whole set of unit tests and build chains in place to try to keep this stuff stable, but for now I'm in between autocomplete solutions. This error no longer happens, but the functionality it provided is still missing.
